### ISSUE TITLE
y30r21

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/etl#50]
- [x] Lav request
- [x] #53
- [x] #54
- [x] Refactor job -> 1 job som trigger alle datasæt som exctracter de relevante datasæt
- [x] Indlæsning via Meta/Data -> Indsættes på SFTP Serveren -> Data Tilgås i SAP/BO
- [x] Skriv dokumentation(jobinsats.md)
- [x] Opsæt CRON-job  og push til CDC

Alle data og alle kommuner. 

Kontanthjælp,
sygedagpenge, 
dagpenge, 
ydelser i alt 

**Dokumentation til brug af API'et**
https://jobindsats.dk/media/fzvhjlqu/api-eksempler.pdf
https://jobindsats.dk/media/myrlvikp/brugerdokumentation.pdf

**Endpoint:** 
https://api.jobindsats.dk/v2/data/y30r21/json

**Comment by nk-randers** [comment]
Transformeret data med den rigtige struktur ud fra Variablerne:
![Image](https://github.com/user-attachments/assets/bd787c84-2509-4ec6-8b31-4ef9992ee1a7)

**Comment by nk-randers** [comment]
Ændret strukturen således der kun er 1 job der kører alle de relevante jobindsats scripts:
![Image](https://github.com/user-attachments/assets/5c212d4d-4225-49b6-815f-d135895be960)

**Comment by nk-randers** [comment]
Opsæt cronjob:
![Image](https://github.com/user-attachments/assets/91b85008-217b-449c-b2d4-1e3e01675107)

Logs fra Argo:
![Image](https://github.com/user-attachments/assets/24feeeae-c6b4-4810-981b-f198ea3f31cb)

Push Meta/Data til CDC:
![Image](https://github.com/user-attachments/assets/4d2e89a3-8849-4133-a30d-717f00a15dba)

**Comment by nk-randers** [comment]
Datasættet [y30r21] fra Jobindsats API'et loades ind i SAP BO:
![Image](https://github.com/user-attachments/assets/2e5deabb-767c-45fd-bd86-5ecf201bca80)
