### ISSUE TITLE
y01a02 - a-dagpenge

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/etl#55]
- [x] Lav request
- [x] Transformer data -> Fjern kolonner med " i alt" 
- [x] Indlæsning via Meta/Data -> Indsættes på SFTP Serveren -> Data Tilgås i SAP/BO
- [x] Opret generiske funktioner som kan bruges på de andre datasæt
- [x] Opsæt cron-job og push til CDC
- [x] Dokumentation

Navngivning: [Data]/[Meta]_SDjobindsast[serienavn]

Fx. Data_SDjobindsatsy01a02

Dimensioner: 
- Køn
- Alder
- Herkomst
(pas på det ikke eksploderer i dimensioner)

OBS: Lav om muligt generiske funktioner der kan genbruges på tværs af datasæt

**Comment by nk-randers** [comment]
Oprettelse af Meta_SA_JobindsatsY01A02.csv:
![Image](https://github.com/user-attachments/assets/6bbf0f2a-2b8a-4073-9c93-0491fff8af3a)

**Comment by nk-randers** [comment]
Opsæt cronjob -> Status:
![Image](https://github.com/user-attachments/assets/91b85008-217b-449c-b2d4-1e3e01675107)

Logs fra Argo:
![Image](https://github.com/user-attachments/assets/24feeeae-c6b4-4810-981b-f198ea3f31cb)

Push Meta/Data til CDC:
![Image](https://github.com/user-attachments/assets/4d2e89a3-8849-4133-a30d-717f00a15dba)

**Comment by nk-randers** [comment]
Tilføjet dokumentation for jobindsats_y01a02

**Comment by nk-randers** [comment]
Datasættet [y01a02] fra Jobindsats API'et loades ind i SAP BO:
![image](https://github.com/user-attachments/assets/23da4fdb-c707-4949-b8c2-1452baf0c1e2)
